spring:
  cloud:
    stream:
      function.definition: supplier;process
      poller:
          fixedDelay: 10000
          initialDelay: 2000          
      bindings:
        supplier-out-0:
          destination: inboundtopic
          producer:
              errorChannelEnabled: true
        process-in-0:
          group: demo-consumer-group
          destination: inboundtopic
          consumer:
            maxAttempts: 3            
        process-out-0:
          destination: outboundtopic
          producer:
              errorChannelEnabled: true
      kafka:
        bindings:                    
            process-in-0:  
                consumer:
                    enableDlq: true
                    dlqName: inboundtopic.dlq
                    configuration:
                        isolation.level: read_committed                        
                        max.poll.records: 1
                        max.poll.interval.ms: 180000
            process-out-0:    
                producer:
                    sync: true                 
            supplier-out-0:
                producer:
                    sync: true                      
        binder:          
          brokers: kafka
          defaultBrokerPort: 9092                    
          minPartitionCount: 1
          autoCreateTopics: true
          autoAddPartitions: true            
          transaction:
            transactionIdPrefix: tx-
            #transaction.timeout.ms: 900000
            transaction.timeout.ms: 1000
            producer:         
                sync: true
                configuration:                  
                  enable.idempotence: true
                  max.in.flight.requests.per.connection: 5
                  retries: 100
                  acks: all
                  max.block.ms: 1000                
                  interceptor:
                      classes: it.poste.democontainer.config.Config$DefaultProducerInterceptor                
logging:
  level:
    org.springframework.kafka.transaction: debug
